In [1]:
import pandas as pd 
import numpy as np 

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
sales = pd.read_csv(r"D:\AnalytixLabs\Data Science & AI\6. Case Studies\Machine Learning Case Studies\4. Capstone Case Study - Finding-Marketing-Insights\Datasets\Online_Sales.csv")
customers = pd.read_excel(r"D:\AnalytixLabs\Data Science & AI\6. Case Studies\Machine Learning Case Studies\4. Capstone Case Study - Finding-Marketing-Insights\Datasets\CustomersData.xlsx")
coupon = pd.read_csv(r"D:\AnalytixLabs\Data Science & AI\6. Case Studies\Machine Learning Case Studies\4. Capstone Case Study - Finding-Marketing-Insights\Datasets\Discount_Coupon.csv")
marketing = pd.read_csv(r"D:\AnalytixLabs\Data Science & AI\6. Case Studies\Machine Learning Case Studies\4. Capstone Case Study - Finding-Marketing-Insights\Datasets\Marketing_Spend.csv")
tax = pd.read_excel(r"D:\AnalytixLabs\Data Science & AI\6. Case Studies\Machine Learning Case Studies\4. Capstone Case Study - Finding-Marketing-Insights\Datasets\Tax_amount.xlsx")

In [3]:
sales.columns = (
    sales.columns
    .str.strip()
    .str.replace(' ', '_')
)

In [4]:
sales.groupby(
    'Product_Description'
)['Quantity'].sum().sort_values(
    ascending=False
).head(20)

Product_Description
Maze Pen                                                  16234
Google 22 oz Water Bottle                                 14282
Google Sunglasses                                         11452
Sport Bag                                                  7321
Google Metallic Notebook Set                               6496
Google Laptop and Cell Phone Stickers                      5847
Google Kick Ball                                           5549
Recycled Paper Journal Set                                 5381
Nest Cam Outdoor Security Camera - USA                     5206
Foam Can and Bottle Cooler                                 5098
Ballpoint LED Light Pen                                    4861
Nest Learning Thermostat 3rd Gen-USA - Stainless Steel     4570
Nest Cam Indoor Security Camera - USA                      4402
Four Color Retractable Pen                                 4394
Leatherette Journal                                        3741
Ballpoint Pen Blue                                         3576
Windup Android                                             3066
Collapsible Shopping Bag                                   2956
Badge Holder                                               2883
Galaxy Screen Cleaning Cloth                               2801
Name: Quantity, dtype: int64

In [5]:
sales['Product_Description'].value_counts().head(20)

Product_Description
Nest Learning Thermostat 3rd Gen-USA - Stainless Steel    3511
Nest Cam Outdoor Security Camera - USA                    3328
Nest Cam Indoor Security Camera - USA                     3230
Google Sunglasses                                         1523
Nest Protect Smoke + CO White Battery Alarm-USA           1361
Nest Learning Thermostat 3rd Gen-USA - White              1089
Nest Protect Smoke + CO White Wired Alarm-USA             1065
Google 22 oz Water Bottle                                  902
Nest Thermostat E - USA                                    844
Google Laptop and Cell Phone Stickers                      806
Nest Cam IQ - USA                                          599
Google Men's 100% Cotton Short Sleeve Hero Tee Black       595
Google Twill Cap                                           546
Google Men's 100% Cotton Short Sleeve Hero Tee White       504
Nest Secure Alarm System Starter Pack - USA                498
Google Men's Vintage Badge Tee Black                       496
BLM Sweatshirt                                             445
Google Men's Bike Short Sleeve Tee Charcoal                431
YouTube Custom Decals                                      419
Sport Bag                                                  408
Name: count, dtype: int64

In [6]:
basket = (
    sales.groupby(
        ['Transaction_ID',
         'Product_Description']
    )['Quantity']
    .sum()
    .unstack()
    .fillna(0)
)

In [8]:
basket

Product_Description,1 oz Hand Sanitizer,20 oz Stainless Steel Insulated Tumbler,22 oz Android Bottle,22 oz YouTube Bottle Infuser,23 oz Wide Mouth Sport Bottle,24 oz YouTube Sergeant Stripe Bottle,25L Classic Rucksack,26 oz Double Wall Insulated Bottle,7&quot; Dog Frisbee,8 pc Android Sticker Sheet,...,YouTube Twill Cap,YouTube Women's Favorite Tee White,YouTube Women's Fleece Hoodie Black,YouTube Women's Racer Back Tank Black,YouTube Women's Short Sleeve Hero Tee Charcoal,YouTube Women's Short Sleeve Tri-blend Badge Tee Charcoal,YouTube Women's Short Sleeve Tri-blend Badge Tee Grey,YouTube Womens 3/4 Sleeve Baseball Raglan White/Black,YouTube Wool Heather Cap Heather/Black,YouTube Youth Short Sleeve Tee Red
Transaction_ID,,,,,,,,,,,,,,,,,,,,,
16679,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16682,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16684,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48494,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48495,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48496,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48497,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
basket = basket.applymap(
    lambda x: 1 if x > 0 else 0
)

C:\Users\adity\AppData\Local\Temp\ipykernel_31740\913560628.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  basket = basket.applymap(

In [18]:
frequent_itemsets = apriori(
    basket,
    min_support=0.005,
    use_colnames=True
)

e:\Anaconda\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [19]:
frequent_itemsets.sort_values(
    by='support',
    ascending=False
).head(20)

     support                                           itemsets
70  0.140098  (Nest Learning Thermostat 3rd Gen-USA - Stainl...
68  0.132796           (Nest Cam Outdoor Security Camera - USA)
67  0.128886            (Nest Cam Indoor Security Camera - USA)
72  0.054307  (Nest Protect Smoke + CO White Battery Alarm-USA)
71  0.043454     (Nest Learning Thermostat 3rd Gen-USA - White)
73  0.042496    (Nest Protect Smoke + CO White Wired Alarm-USA)
75  0.033678                          (Nest Thermostat E - USA)
27  0.032162            (Google Laptop and Cell Phone Stickers)
48  0.027692                                (Google Sunglasses)
88  0.027653  (Nest Cam Outdoor Security Camera - USA, Nest ...
20  0.027293                        (Google 22 oz Water Bottle)
65  0.023902                                (Nest Cam IQ - USA)
51  0.021787                                 (Google Twill Cap)
29  0.020271  (Google Men's 100% Cotton Short Sleeve Hero Te...
74  0.019872      (Nest Secure Alarm System Starter Pack - USA)
40  0.017956             (Google Men's Vintage Badge Tee Black)
32  0.016999  (Google Men's 100% Cotton Short Sleeve Hero Te...
82  0.016719                            (YouTube Custom Decals)
3   0.016280               (26 oz Double Wall Insulated Bottle)
78  0.016280                                        (Sport Bag)

In [20]:
rules = association_rules(
    frequent_itemsets,
    metric='lift',
    min_threshold=1
)

In [21]:
rules.sort_values(
    by='lift',
    ascending=False
).head(20)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1,(YouTube Custom Decals),(Google Laptop and Cell Phone Stickers),0.016719,0.032162,0.005347,0.319809,9.943840,1.0,0.004809,1.422892,0.914729,0.122823,0.297206,0.243031
0,(Google Laptop and Cell Phone Stickers),(YouTube Custom Decals),0.032162,0.016719,0.005347,0.166253,9.943840,1.0,0.004809,1.179352,0.929324,0.122823,0.152076,0.243031
2,(Nest Cam Outdoor Security Camera - USA),(Nest Cam Indoor Security Camera - USA),0.132796,0.128886,0.027653,0.208233,1.615644,1.0,0.010537,1.100216,0.439403,0.118159,0.091088,0.211392
3,(Nest Cam Indoor Security Camera - USA),(Nest Cam Outdoor Security Camera - USA),0.128886,0.132796,0.027653,0.214551,1.615644,1.0,0.010537,1.104087,0.437430,0.118159,0.094274,0.211392
8,(Nest Protect Smoke + CO White Wired Alarm-USA),(Nest Learning Thermostat 3rd Gen-USA - Stainl...,0.042496,0.140098,0.007222,0.169953,1.213100,1.0,0.001269,1.035968,0.183462,0.041183,0.034719,0.110753
9,(Nest Learning Thermostat 3rd Gen-USA - Stainl...,(Nest Protect Smoke + CO White Wired Alarm-USA),0.140098,0.042496,0.007222,0.051552,1.213100,1.0,0.001269,1.009548,0.204286,0.041183,0.009458,0.110753
6,(Nest Learning Thermostat 3rd Gen-USA - Stainl...,(Nest Protect Smoke + CO White Battery Alarm-USA),0.140098,0.054307,0.009018,0.064369,1.185272,1.0,0.001410,1.010754,0.181778,0.048644,0.010639,0.115212
7,(Nest Protect Smoke + CO White Battery Alarm-USA),(Nest Learning Thermostat 3rd Gen-USA - Stainl...,0.054307,0.140098,0.009018,0.166054,1.185272,1.0,0.001410,1.031125,0.165288,0.048644,0.030185,0.115212
4,(Nest Cam Outdoor Security Camera - USA),(Nest Protect Smoke + CO White Battery Alarm-USA),0.132796,0.054307,0.007661,0.057692,1.062327,1.0,0.000449,1.003592,0.067654,0.042695,0.003579,0.099383
5,(Nest Protect Smoke + CO White Battery Alarm-USA),(Nest Cam Outdoor Security Camera - USA),0.054307,0.132796,0.007661,0.141073,1.062327,1.0,0.000449,1.009636,0.062039,0.042695,0.009544,0.099383

In [22]:
rules = rules[
    [
        'antecedents',
        'consequents',
        'support',
        'confidence',
        'lift'
    ]
]

In [23]:
rules['antecedents'] = (
    rules['antecedents']
    .apply(lambda x: ', '.join(list(x)))
)

rules['consequents'] = (
    rules['consequents']
    .apply(lambda x: ', '.join(list(x)))
)

In [24]:
top_rules = rules.sort_values(
    by='lift',
    ascending=False
)

top_rules.head(20)

,antecedents,consequents,support,confidence,lift
1,YouTube Custom Decals,Google Laptop and Cell Phone Stickers,0.005347,0.319809,9.943840
0,Google Laptop and Cell Phone Stickers,YouTube Custom Decals,0.005347,0.166253,9.943840
2,Nest Cam Outdoor Security Camera - USA,Nest Cam Indoor Security Camera - USA,0.027653,0.208233,1.615644
3,Nest Cam Indoor Security Camera - USA,Nest Cam Outdoor Security Camera - USA,0.027653,0.214551,1.615644
8,Nest Protect Smoke + CO White Wired Alarm-USA,Nest Learning Thermostat 3rd Gen-USA - Stainle...,0.007222,0.169953,1.213100
9,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest Protect Smoke + CO White Wired Alarm-USA,0.007222,0.051552,1.213100
6,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest Protect Smoke + CO White Battery Alarm-USA,0.009018,0.064369,1.185272
7,Nest Protect Smoke + CO White Battery Alarm-USA,Nest Learning Thermostat 3rd Gen-USA - Stainle...,0.009018,0.166054,1.185272
4,Nest Cam Outdoor Security Camera - USA,Nest Protect Smoke + CO White Battery Alarm-USA,0.007661,0.057692,1.062327
5,Nest Protect Smoke + CO White Battery Alarm-USA,Nest Cam Outdoor Security Camera - USA,0.007661,0.141073,1.062327

In [25]:
top_rules.to_csv(
    'market_basket_rules.csv',
    index=False
)

In [26]:
top_rules[['antecedents','consequents','support','confidence','lift']]

,antecedents,consequents,support,confidence,lift
1,YouTube Custom Decals,Google Laptop and Cell Phone Stickers,0.005347,0.319809,9.943840
0,Google Laptop and Cell Phone Stickers,YouTube Custom Decals,0.005347,0.166253,9.943840
2,Nest Cam Outdoor Security Camera - USA,Nest Cam Indoor Security Camera - USA,0.027653,0.208233,1.615644
3,Nest Cam Indoor Security Camera - USA,Nest Cam Outdoor Security Camera - USA,0.027653,0.214551,1.615644
8,Nest Protect Smoke + CO White Wired Alarm-USA,Nest Learning Thermostat 3rd Gen-USA - Stainle...,0.007222,0.169953,1.213100
9,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest Protect Smoke + CO White Wired Alarm-USA,0.007222,0.051552,1.213100
6,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest Protect Smoke + CO White Battery Alarm-USA,0.009018,0.064369,1.185272
7,Nest Protect Smoke + CO White Battery Alarm-USA,Nest Learning Thermostat 3rd Gen-USA - Stainle...,0.009018,0.166054,1.185272
4,Nest Cam Outdoor Security Camera - USA,Nest Protect Smoke + CO White Battery Alarm-USA,0.007661,0.057692,1.062327
5,Nest Protect Smoke + CO White Battery Alarm-USA,Nest Cam Outdoor Security Camera - USA,0.007661,0.141073,1.062327